[package]
authors = ["Jonathan Brouwer"]
name = "increment"
version = "0.1.0"
edition = "2018"

[dependencies]
pyo3 = { version = "0.9.0-alpha.1", features = ["extension-module"] }

[lib]
name = "increment"
crate-type = ["cdylib"]
