[package]
authors = ["Messense Lv <messense@icloud.com>"]
name = "word-count"
version = "0.1.0"
edition = "2018"

[dependencies]
pyo3 = { features = ["extension-module"] }

[lib]
name = "word_count"
crate-type = ["cdylib"]
