[package]
name = "python_rust_calls"
version = "0.1.0"
authors = ["JonathanBrouwer <j.t.brouwer@student.tudelft.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dyn"
crate-type = ["dylib"]

[dependencies]
